### ISSUE TITLE
Dependency on BitMagic

### ISSUE THREAD

**Issue by science-enthusiast** [FellegaraR/Tetrahedral_trees#1]
While building the project, an error occurs due to dependency on the header file bm/bm.h from BitMagic. The project builds successfully after installing BitMagic. Maybe, installing BitMagic can also be mentioned along with Boost and qmake.

**Comment by FellegaraR** [comment]
thanks for noticing it! I updated the readme.

That said, on debian/ubuntu OS, just type in the terminal: sudo apt install bmagic
